### ISSUE TITLE
Best practice for vcr-enabled tests on CRAN

### ISSUE THREAD

**Issue by dpprdan** [ropensci/vcr#102]
I've [started](https://github.com/dpprdan/opencage/commit/716e6e17ea40b4d51485efcaa7523d197f03b64c) using {vcr} for the tests in {[opencage](https://github.com/ropensci/opencage)},  but I am unsure, what the best practices are regarding running the tests on CRAN (or not). 

I have seen that some of the tests that use vcr in other packages `skip_on_cran()`, but not all, e.g. https://github.com/ropensci/worrms/blob/master/tests/testthat/test-wm_children.R

So it seems to be possible to run these tests on CRAN? Is there anything one has to keep in mind? E.g. where should the cassettes ideally go (for {opencage} I stored them in `tests/vcr_cassettes`)?

**Comment by dpprdan** [comment]
I guess one (obvious?) thing to keep in mind would be to create the cassettes by running e.g. `devtools::test()`.

**Comment by sckott** [comment]
Yes, it is possible to run tests on CRAN that use cassettes on disk. I think at first when vcr was just on CRAN I was skipping tests that used vcr until I was sure it worked on CRAN checks, but it should be fine now to run tests that use vcr on CRAN

I don't know the scope of what's allowed for running tests on CRAN - but it has worked to have them in `tests/` somewhere. I've used `tests/vcr_cassettes` and `tests/fixtures/vcr_cassettes`

One thing to note is that if you have your cassettes in `.gitignore` then your cassetttes won't be pushed up to github and tests wouldn't have access to them in remote locations. I think Adam Sparks had done this. 

wrt using `devtools::test()` first: i'll play around with that and have a look - but I'd guess that yes, one would need to run that first if `check()` uses a tempdir

**Comment by dpprdan** [comment]
Thanks! We're all set then, it seems. 🎉 

> One thing to note is that if you have your cassettes in `.gitignore` then your cassetttes won't be pushed up to github and tests wouldn't have access to them in remote locations.

The same applies to `.Rbuildignore`, I suppose.

Do you want to add "vcr-enabled tests on CRAN" to the docs/README/HTTP-testing-book?

**Comment by sckott** [comment]
right, same-ish for .Rbuildignore

> Do you want to add "vcr-enabled tests on CRAN" to the docs/README/HTTP-testing-book?

sure, what exactly are you thinking? e.g., how can this section https://github.com/ropensci/vcr#vcr-for-tests be improved

**Comment by sckott** [comment]
see new section https://ropenscilabs.github.io/http-testing-book/vcr-intro.html#vcr-enabled-testing in the book
