### ISSUE TITLE
nasapower no longer uses vcr

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#114]
So it should be removed from the README

https://github.com/ropensci/nasapower/commit/2449135bbf1a6f5d2c77c42a0dc2ec3e7c352223

**Comment by sckott** [comment]
thanks

**Comment by adamhsparks** [comment]
Sorry, yes, I removed it. I just had too many issues getting it to work so I gave up and removed it.

**Comment by sckott** [comment]
no worries
