### ISSUE TITLE
Use_vcr_test?

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#115]
I'm starting to use vcr in a package, so here come all the stupid questions/ideas.

The `use_vcr()` function creates an example test file.

Could there be a function that'd be like `usethis::use_test()` to set up individual test files with the correct vcr syntax?

E.g. `use_vcr_test("get_deals")` would create

```r
test_that("get_deals works", {
  vcr::use_cassette("get_deals", {
    res <- get_deals()
  })
  # expect_
})

```

[without `context()`](https://www.tidyverse.org/articles/2019/04/testthat-2-1-0/#context-is-now-optional).

I'm not entirely sure my suggestion is a good idea. I'm currently copy-pasting a lot hence the idea.

**Comment by maelle** [comment]
Or is it better to wrap the test inside the cassette, actually? The README mentions the two, but how do I choose? :-) 

I like the idea of wrapping the test because I have existing tests, so it's easier to add the wrapping to them.

**Comment by sckott** [comment]
yeah, i guess here https://github.com/ropensci/vcr#vcr-for-tests i should just remove the first code block and say do it the 2nd way, as the 2nd way is better - it's a bit more work to move lines around, but worth it I think

about use_test idea: i'd think it'd only make sense if someone's writing a new test and hasn't used vcr before; i'd think most people would be modifying currently existing tests, but that's just a guess. it'd be cool if we could automatically insert the use_cassette line and move lines around to the ideal locations, seems complicated though
