### ISSUE TITLE
What if I mistakenly use the same cassette name twice?

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#116]
Will this be checked before the tests are run?

**Comment by sckott** [comment]
good question. im pretty sure you'd get an error about the http request not matching whats on the cassette, but if it was for some reason the same http request, then that'd be bad cause it'd give back the wrong data presumably 

I like the idea to check before tests are run - might be able to do that in the `helper-packagename.R` file used, after setting the vcr configuration

**Comment by sckott** [comment]
@maelle can you try this out?  `remotes::install_github("ropensci/vcr@check-cassette-names")`, then put this in your `helper-pkgname.R` file:

```
vcr::check_cassette_names()
```

**Comment by sckott** [comment]
if you don't have any duplicated cassette names, just create a duplicate and run tests again

**Comment by maelle** [comment]
Thank you, and sorry for delay testing it!

* Could the message

```r
Error: you should not have duplicated cassette names:
    api-usage
```

include the filenames where the cassette name was found? E.g.

```r
Error: you should not have duplicated cassette names:
    api-usage (found in test-blabla.R, test-blabla2.R)
```

* Duplicate cassette names are obviously bad. Could the docs for the function also state what else is bad in a cassette name and why?

* Does `use_vcr()` add this function to the `helper-pkgname.R`?

**Comment by sckott** [comment]
@maelle okay, made those changes, when you get a chance can you try again?

**Comment by maelle** [comment]
Thank you!

* Yes the error message is more informative now with filenames, awesome!

* The new docs look great! Why not store that in an Rmd fragment to re-use in a vignette + in the README? Cf https://blog.r-hub.io/2019/12/03/readmes/#re-use-of-rmd-portions-in-other-rmds

* It is obvious but you could add that the function cannot check the names are meaningful. Maybe it'd be useful to say why you might want to know to which test a cassette belongs: e.g. to delete them when you've edited a function (the last two days I deleted many cassettes whilst editing code and was glad they had good names :-) ).

**Comment by sckott** [comment]
thanks !

**Comment by sckott** [comment]
done
