### ISSUE TITLE
How to add a single test

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#120]
I have a test suite for which I had created vcr cassettes.

Now if I had a test inside a file, say

```r
vcr::use_cassette("get_owners_active", {
  test_that("get_owners works with includeInactive", {
    res <- get_owners(include_inactive = FALSE)
    expect_is(res, "list")
    expect_true(all(lengths(purrr::map(res, "remoteList")) > 0))
  })
})
```

in a file where I have another cassette. I checked the cassette name, it's unique.

when I run the tests I get

```r
An HTTP request has been made that vcr does not know how to handle:
GET https://api.hubapi.com/owners/v2/owners?includeInactive=TRUE&hapikey=demo
vcr is currently using the following cassette:
  - ../fixtures/get_owners.yml
    - record_mode: once
    - match_requests_on: method, uri


Under the current configuration vcr can not find a suitable HTTP interaction
to replay and is prevented from recording new requests. There are a few ways
you can deal with this:

  * If you're surprised vcr is raising this error
    and want insight about how vcr attempted to handle the request,
    you can use 'logging' to see more details [1].

  * You can use the :new_episodes record mode to allow vcr to
    record this new request to the existing cassette [2].

  * If you want vcr to ignore this request (and others like it), you can
    set an `ignore_request` function [3].

  * The current record mode ('once') does not allow new requests to be recorded
    to a previously recorded cassette. You can delete the cassette file and re-run
    your tests to allow the cassette to be recorded with this request [4].

  * The cassette contains 1 HTTP interaction that has not been
    played back. If your request is non-deterministic, you may need to
    change your 'match_requests_on' cassette option to be more lenient
    or use a custom request matcher to allow it to match [5].

[1] https://ropenscilabs.github.io/http-testing-book/logging

[2] https://ropenscilabs.github.io/http-testing-book/record-modes.html#new_episodes

[3] https://ropenscilabs.github.io/http-testing-book/vcr-configuration#config-ignore-requests

[4] https://ropenscilabs.github.io/http-testing-book/record-modes.html#once

[5] https://ropenscilabs.github.io/http-testing-book/request-matching
```

* It's a bit long error output for a test
* I was expecting vcr to simply create the cassette the first time that test is run as it did the first time I switched to having cassettes for all tests.

What I do now is erasing the fixtures folder and then running the tests again a first time to create all cassettes, which does not sound optimal.

**Comment by maelle** [comment]
Note that yes the existing tests include one for a cassette called "get_owners".

**Comment by sckott** [comment]
the error has `../fixtures/get_owners.yml` - so it **shouldn't** be coming from the block you showed above it with cassette name `get_owners_active` - most likely there was some change in the code block that uses the get_owners cassette, thoughts?

> I was expecting vcr to simply create the cassette the first time that test is run as it did the first time I switched to having cassettes for all tests.

It should create a cassette the first time that test is run. Maybe this is related to the get_owners vs. get_owners_active above?

The error message is somewhat verbose, copied from ruby's message. I could make it smaller, i guess could send people to the book section on error messages

**Comment by maelle** [comment]
Aaah probably my fault, sorry!

**Comment by sckott** [comment]
maybe not - did you check if there was a change in the block of code that uses the get_owners cassette?

**Comment by maelle** [comment]
Yes I now realize I started explicitly passing an argument with the default value in my query (so the result was the same but not the request)... sorry and thanks 🙈
