### ISSUE TITLE
more brief cassette error message?

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#121]
from #120 could just report that top part about the cassette and request, then say go to the book and/or  issue tracker

**Comment by maelle** [comment]
Or you could have a function called `vcr_help()` that'd print all the message that's currently printed to screen, and in e.g. tests (using the env variable that tells you whether the code is run in a test) the message would be "Error short blabla, run vcr::vcr_help()" or so?

**Comment by sckott** [comment]
Possibly, I am re-factoring the error handler so the message gets created and stored, and then used as needed - so could store the full message in an environment
