### ISSUE TITLE
document vcr_turn_off/et al. env vars better

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#131]
via #37 

https://github.com/ropensci/vcr/issues/37#issuecomment-566212328 and my comment after

**Comment by maelle** [comment]
I was thinking that for these variables and other lightswitch options a decision tree would be good (a diagram, or in text form).

You want to turn off vcr...

* in a single test, blabla

* in all tests, blabla

well with more decision criteria.

**Comment by sckott** [comment]
good idea!
