### ISSUE TITLE
Cassette options in vcr configuration are ignored

### ISSUE THREAD

**Issue by aaronwolen** [ropensci/vcr#151]
The following cassette options can be set w/ `vcr_configure()`

- `record`
- `match_requests_on`
- `re_record_interval`
- `clean_outdated_http_interactions`
- `allow_unused_http_interactions`
- `serialize_with`
- `persist_with`
- `preserve_exact_body_bytes`

but aren't actually used anywhere. It seems like `insert_cassette()` and `use_cassette()` should inherit values for those params from `vcr_c` rather than providing their own defaults. 

Quick example that highlights where the current behavior deviates from my expectation:

``` r
devtools::dev_mode(on = TRUE)
#> Dev mode: ON
library(vcr)

vcr_configure(
  record = "none",
  match_requests_on = "body",
  preserve_exact_body_bytes = TRUE
)
#> <vcr configuration>
#>   Cassette Dir: .
#>   Record: none
#>   URI Parser: crul::url_parse
#>   Match Requests on: body
#>   Preserve Bytes?: TRUE
#>   Logging?: FALSE
#>   ignored hosts: 
#>   ignore localhost?: FALSE
#>   Write disk path:

cas <- insert_cassette("configured-insert")

# expected "none"
cas$record
#> [1] "once"

# expected "body"
cas$match_requests_on
#> [1] "method" "uri"

# expected 
cas$preserve_exact_body_bytes
#> [1] FALSE
```

<sup>Created on 2020-02-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sckott** [comment]
Thanks for raising this issue. I agree that `insert_cassette()` and `use_cassette()` should inherit from whatever the user sets with `vcr_configure()` - but that the 2 former functions can override those defaults if the user sets them. i guess we set all those parameters to default of `NULL` in `insert_cassette()` and `use_cassette()` ?
