### ISSUE TITLE
getting started and use_vcr

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#170]
based in part on https://github.com/ropensci/vcr/issues/169 i think we need a better/more clear/easy to use Getting Started section in the docs and in the book. Set of a few steps to get started using vcr in a package. And we need to make more clear that `use_vcr` should be the first step

**Comment by DaveParr** [comment]
If you'd like I'd be happy to take a first pass at the write up in the docs? If you'd rather someone with a bit more knowledge of the project did it though, that's great too. 👍

**Comment by sckott** [comment]
Thanks for volunteering @DaveParr  !  I think a getting started section above the Usage section in the README here https://github.com/ropensci/vcr#usage and in the getting started vignette here https://docs.ropensci.org/vcr/articles/vcr.html would be great. If you submit a PR we can see if any changes should be made, etc.

**Comment by DaveParr** [comment]
No sweat. Will have a look at it in the next few days :)

**Comment by alex-gable** [comment]
fwiw, I was flummoxed by how hard it was to find `use_vcr`.

it was frustrating not being able to reproduce the examples in either the [vcr introduction](https://docs.ropensci.org/vcr/articles/vcr.html) or the [http testing in R book](https://books.ropensci.org/http-testing/).

honestly I didn't really "get it" until I saw and used the [catfact repo](https://github.com/alex-gable/catfact).  

I'd wonder if producing a package like this and the included tests from scratch might be a more practical introduction?

**Comment by sckott** [comment]
Thanks for the feedback @alex-gable Yeah, I agree use_vcr should have been easier to find. PR #171 should help fix that. 

> I'd wonder if producing a package like this and the included tests from scratch might be a more practical introduction?

That's a good idea. Would it make sense to include that as a vignette in the package and as part of the book?

**Comment by sckott** [comment]
@DaveParr  you can do the vignette PR if you want - or I can do later

**Comment by alex-gable** [comment]
@sckott sorry I was late to this one, but appreciate the quick turnaround. appreciate the help @DaveParr!
