### ISSUE TITLE
default secret purging?

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#182]
From httptest docs "By default, capture_requests will now purge any credentials contained in cookies, standard HTTP request headers, basic HTTP authentication methods, and OAuth token management objects."

**Comment by sckott** [comment]
hmm, maybe. something to consider. Ruby webmock doesn't do this though, so just thinking of the wisdom of lots of previous experience, maybe it's not warranted or a good idea. will have to think about it more.

**Comment by maelle** [comment]
related to #58 (fine if it is not a good idea, just noting it is a related topic)

**Comment by sckott** [comment]
I think i'll implement filtering of headers (`filter_headers`) - similar to what's in vcrpy https://vcrpy.readthedocs.io/en/latest/advanced.html#filter-information-from-http-headers and possibly other filter options, for body and query string

**Comment by maelle** [comment]
Yay 🐍

**Comment by sckott** [comment]
thanks for pinging that other related issue. 

i don't' think i agree with the idea of removing potentially sensitive fields/data by default. but i think we should make it as easy as possible and document it well

**Comment by maelle** [comment]
and having warnings would help not make mistakes (says someone who recently made a mistake :cold_sweat: )

**Comment by sckott** [comment]
Right, we could throw warnings if we detect a potential sensitive string

**Comment by sckott** [comment]
warnings in separate issue: #82

**Comment by maelle** [comment]
is the header filtering on the milestone for next release? I think it'd be really great for developers of packages with OAuth (so, for me :joy: ).

**Comment by sckott** [comment]
i'll put it on for next release milestone, but i haven't tried this yet, so don't know how long it will take

**Comment by maelle** [comment]
Fingers crossed!

**Comment by sckott** [comment]
- request headers: 
    - remove headers from fixtures? yes
    - remove header values from fixtures? yes
    - put back header values in response? yes 
- response headers:
    - remove headers from fixtures? yes
    - remove header values from fixtures? yes
    - put back header values in response? no
