### ISSUE TITLE
using library(vcr) is actually mandatory

### ISSUE THREAD

**Issue by KevCaz** [ropensci/vcr#185]
Hi @sckott, 

I have used `vcr` successfully today. There is one thing that was not clear to me until I looked at the code: `library(vcr)` is actually mandatory otherwise yaml files written are empty. My understanding is that is because of the initialization, i.e. the call to `.onLoad()`. 

I think it would be worth mentioning this is the documentation and in the `herper*` file created by `vcr::use_vcr()` 

```R
# a comment here?
library("vcr")
invisible(vcr::vcr_configure(
  dir = "../fixtures"
))
vcr::check_cassette_names()
```

Maybe a comment line saying that `library("vcr")` is required even though the package namespace is used below. 

Anyway, thank you for your work on this package.

**Comment by sckott** [comment]
Thanks @KevCaz , good idea!  You specifically mean just in the helper file, correct?

**Comment by KevCaz** [comment]
In the helper file yes! And maybe one mention in the readme? In this block :arrow_down: (could be the same comment as in the helper file)

https://github.com/ropensci/vcr/blob/be3ab9c6d93b258967f4cb4ae6bcceadfadca112/README.Rmd#L65-L71

**Comment by KevCaz** [comment]
BTW, I can totally do it in a PR.

**Comment by sckott** [comment]
thanks, a PR would be great!
