### ISSUE TITLE
add link to a pkg repo using vcr for testing

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#19]
to show an example, e.g. in the README say "you can see `vcr` in action for testing in foo"

**Comment by maelle** [comment]
Ok then I volunteer 🙋 , just get prepared to get many questions.

**Comment by maelle** [comment]
The README now seems to have the corresponding section so feel free to close this (and #20 that actually doesn't even make sense?)

**Comment by sckott** [comment]
sounds good , will close

i think leave #20 open - i think you meant perhaps someone can use vcr within a vignette to cache http requests in the code chunks
