### ISSUE TITLE
provide a custom testthat skipper?

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#191]
that'd be `skip_if_vcr_off()`

**Comment by sckott** [comment]
the use case is if user has turned off vcr with env var and then want to make sure test won't run if vcr off?

**Comment by maelle** [comment]
Yes because they'd be tests with an edited cassette for instance

**Comment by sckott** [comment]
yeah, probably doable

**Comment by maelle** [comment]
I think I could even try and make a PR
