### ISSUE TITLE
Add an article or two for covering cassette management

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#197]
* When to delete a cassette and re-record it. (maybe in the debugging article? an out-of-date cassette is a common reason for test failure after all)

* how and why to edit your cassettes by hand or with a script with the `yaml` package
   * to test for error behavior without having to learn webmockr
   * to test for sequence of requests (e.g. 502 then 200) without having to learn webmockr
   * if you edit a cassette you might want to add `skip_if_vcr_off()`.
   * we imagine you will edit cassette by hand but you could also imagine writing a script to make your edits reproducible (using the yaml package if your cassettes are YAML; using jsonlite if your cassettes are JSON). However it might be more work than it's worth; editing cassettes by hand is perfectly fine.

**Comment by sckott** [comment]
That sounds good.

**Comment by maelle** [comment]
added a section about deleting cassettes in the debugging vignette PR

**Comment by maelle** [comment]
I will work on a vignette about editing cassettes by hand once #195 because the skipper is needed when you edit cassettes by hand.

**Comment by sckott** [comment]
ok, thanks
