### ISSUE TITLE
On OAuth and secret purging

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#200]
Cf https://github.com/rladies/meetupr/pull/84

My biggest fear with OAuth is that at the time of vcr configuration there is a token but what if it gets refreshed later whilst running the tests and recording? Then it is in my cassettes, not in my config.

So I would really like a way to say that what is supposed to be edited is the authorization header, that would not be a regular expression.

**Comment by maelle** [comment]
It might be included in other issues about secret purging, but I wanted to report my experience in case it is relevant 🙂

**Comment by sckott** [comment]
Even if a oauth token changes, as long as you use the same env var name to get the token then it should work.  

I think the targeted specific header filtering will address this https://github.com/ropensci/vcr/issues/182#issuecomment-730494747

**Comment by maelle** [comment]
The problem is that it can't be an environment variable, or at least isn't in the workflow I have seen.

Great reg targeted header filtering!

**Comment by maelle** [comment]
Duplicate of #182
