### ISSUE TITLE
is there an alternative to preserve_exact_body_bytes for Windows?

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#203]
Asking because the cassettes are much less nice to look at in that case.

Editing them by hand would not be fun.

**Comment by maelle** [comment]
I think that yes and it is using JSON as serializer?! so nice. 

See https://github.com/maelle/vcrencoding/actions/runs/386840954

And then if I switch back to YAML I get the control character error (which is when YAML finds a ":" where it does not expect it) https://github.com/maelle/vcrencoding/runs/1463078832?check_suite_focus=true#step:9:204

**Comment by sckott** [comment]
Hmm, JSON serializer isn't exactly an alternative to preserve bytes option. You can still use preserve bytes when using JSON serializer.  

I think there's no error for windows when you use json serializer b/c you're avoiding using the yaml pkg, which i think causes that error.

**Comment by maelle** [comment]
Oh yeah that is what I mean. I wanted no encoding error but human readable cassettes ☺
