### ISSUE TITLE
Could the JSON cassettes be prettier?

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#205]
I.e. with more new lines, to be as human readable as YAML cassettes are.

**Comment by maelle** [comment]
oooh I see json_pretty. I suppose I disagree with the default? :thinking:

**Comment by sckott** [comment]
i thought it made sense to not do pretty by default to save disk space - should compare files of various sizes with and without pretty

**Comment by sckott** [comment]
i use sublime text editor and it has a jq plugin, so I can prettify a json file that way. does rstudio (I assume what most users using vcr will be using) have a way to prettify json?

**Comment by maelle** [comment]
you mean to save it in an ugly format but see it in a pretty way? Not that I know of.

**Comment by sckott** [comment]
I think we should keep this by default as `json_pretty=FALSE` for now, and consider changing if users want it changed. Sound good?

**Comment by maelle** [comment]
Yes!

**Comment by sckott** [comment]
okay, thanks
