### ISSUE TITLE
Add a filter helper for query?

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#212]
Like "Filter information from HTTP querystring" in vcpy

**Comment by maelle** [comment]
From vcpy docs I also like the callback in case the built-in filtering isn't enough. :eyes:

**Comment by sckott** [comment]
Yes, saw that, and for body as well.

**Comment by maelle** [comment]
I want them all! 😁

**Comment by maelle** [comment]
Re-opening as I think https://github.com/ropensci/vcr/blob/master/man/rmdhunks/configuration-vignette.Rmd needs updating too :slightly_smiling_face:

**Comment by maelle** [comment]
(I noticed as I wanted to send the link to the docs to someone :smile_cat: )

**Comment by sckott** [comment]
thanks, will do @maelle

**Comment by sckott** [comment]
@maelle updated docs https://docs.ropensci.org/vcr/articles/configuration.html#filter-query-parameters

**Comment by maelle** [comment]
Thank you!
