### ISSUE TITLE
filter_request_header adds a header

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#213]
See  https://github.com/maelle/exemplighratia/pull/2/files

In https://github.com/maelle/exemplighratia/blob/vcrtest/tests/fixtures/gh_api_status.yml there is actually no Authorization header in the HTTP request made, but vcr's filtering adds it. I would have expected vcr to replace the header with the value when the header exists to begin with.

**Comment by sckott** [comment]
Hmm, not sure off the top. I guess it's a bit of an edge case in that I wouldn't expect a user to filter out a header they think they don't have. But, definitely should be fixed.

**Comment by maelle** [comment]
Well the configuration is for all tests and you won't have the same headers in all requests so it might actually be quite common?

**Comment by sckott** [comment]
@maelle fixed now
