### ISSUE TITLE
should vcr::use_vcr() add a dependency on vcr current version

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#214]
I.e. right now it adds "vcr" under Suggests but shouldn't it add "vcr ( >= 0.6.0)" as dependency, or whatever the current version is?

**Comment by sckott** [comment]
Hmm, maybe. I guess it depends on the features of the pkg one is using, right?

**Comment by maelle** [comment]
Well there is `vcr::vcr_test_path()` used in the setup file and not available in previous versions

**Comment by sckott** [comment]
Right, if use_vcr is adding vcr_test_path then yeah should have min v0.6. But I forget, are Suggests pkg versions respected when installing a pkg, running check?

**Comment by maelle** [comment]
I would hope so 🤔

**Comment by sckott** [comment]
We'll have to use the last version on CRAN for this. Will need to be updated manually as we don't want to have an http request to get the version that might fail
