### ISSUE TITLE
vcr creates empy cassette

### ISSUE THREAD

**Issue by llrs** [ropensci/vcr#224]
I come here from https://github.com/ropensci-books/http-testing/issues/84.

If I have a function that calls a resource like this:

```r
f <- function() {
    xml2::read_xml("https://bugs.r-project.org/bugzilla/show_bug.cgi?id=1&ctype=xml")
}
```

And I test it with:

```r
test_that("f works", {
    vcr::use_cassette("get_issue", {
        gi <- f()
    })
})
```

Then it creates an [empty cassette](https://github.com/llrs/bugRzilla/blob/master/tests/fixtures/get_issue.yml). What would be the right way to test this? Or perhaps I need to configure something differently than from the default?

<details> <summary><strong>Session Info</strong></summary>

```r
? Session info ????????????????????????????????????????????????????????????????????????
 setting  value                       
 version  R version 4.0.1 (2020-06-06)
 os       Ubuntu 20.04.2 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Madrid               
 date     2021-02-14                  

? Packages ????????????????????????????????????????????????????????????????????????????
 ! package     * version   date       lib source        
   assertthat    0.2.1     2019-03-21 [1] CRAN (R 4.0.1)
   backports     1.2.1     2020-12-09 [1] CRAN (R 4.0.1)
   base64enc     0.1-3     2015-07-28 [1] CRAN (R 4.0.1)
   BiocManager * 1.30.10   2019-11-16 [1] CRAN (R 4.0.1)
 R bugRzilla   * 0.0.90001 <NA>       [?] <NA>          
   cachem        1.0.3     2021-02-04 [1] CRAN (R 4.0.1)
   callr         3.5.1     2020-10-13 [1] CRAN (R 4.0.1)
   cli           2.3.0     2021-01-31 [1] CRAN (R 4.0.1)
   covr          3.5.1     2020-09-16 [1] CRAN (R 4.0.1)
   crayon        1.4.1     2021-02-08 [1] CRAN (R 4.0.1)
   crosstalk     1.1.1     2021-01-12 [1] CRAN (R 4.0.1)
   crul          1.0.0     2020-07-30 [1] CRAN (R 4.0.1)
   curl          4.3       2019-12-02 [1] CRAN (R 4.0.1)
   cyclocomp   * 1.1.0     2016-09-10 [1] CRAN (R 4.0.1)
   desc          1.2.0     2018-05-01 [1] CRAN (R 4.0.1)
   devtools    * 2.3.2     2020-09-18 [1] CRAN (R 4.0.1)
   diffobj       0.3.3     2021-01-07 [1] CRAN (R 4.0.1)
   digest        0.6.27    2020-10-24 [1] CRAN (R 4.0.1)
   DT            0.17      2021-01-06 [1] CRAN (R 4.0.1)
   ellipsis      0.3.1     2020-05-15 [1] CRAN (R 4.0.1)
   evaluate      0.14      2019-05-28 [1] CRAN (R 4.0.1)
   fansi         0.4.2     2021-01-15 [1] CRAN (R 4.0.1)
   fastmap       1.1.0     2021-01-25 [1] CRAN (R 4.0.1)
   fauxpas       0.5.0     2020-04-13 [1] CRAN (R 4.0.1)
   fs            1.5.0     2020-07-31 [1] CRAN (R 4.0.1)
   glue          1.4.2     2020-08-27 [1] CRAN (R 4.0.1)
   htmltools     0.5.1.1   2021-01-22 [1] CRAN (R 4.0.1)
   htmlwidgets   1.5.3     2020-12-10 [1] CRAN (R 4.0.1)
   httpcode      0.3.0     2020-04-10 [1] CRAN (R 4.0.1)
   httr          1.4.2     2020-07-20 [1] CRAN (R 4.0.1)
   jsonlite      1.7.2     2020-12-09 [1] CRAN (R 4.0.1)
   knitr         1.31      2021-01-27 [1] CRAN (R 4.0.1)
   lazyeval      0.2.2     2019-03-15 [1] CRAN (R 4.0.1)
   lifecycle     0.2.0     2020-03-06 [1] CRAN (R 4.0.1)
   magrittr      2.0.1     2020-11-17 [1] CRAN (R 4.0.1)
   memoise       2.0.0     2021-01-26 [1] CRAN (R 4.0.1)
   pillar        1.4.7     2020-11-20 [1] CRAN (R 4.0.1)
   pkgbuild      1.2.0     2020-12-15 [1] CRAN (R 4.0.1)
   pkgconfig     2.0.3     2019-09-22 [1] CRAN (R 4.0.1)
   pkgload       1.1.0     2020-05-29 [1] CRAN (R 4.0.1)
   prettyunits   1.1.1     2020-01-24 [1] CRAN (R 4.0.1)
   processx      3.4.5     2020-11-30 [1] CRAN (R 4.0.1)
   ps            1.5.0     2020-12-05 [1] CRAN (R 4.0.1)
   purrr         0.3.4     2020-04-17 [1] CRAN (R 4.0.1)
   R.cache       0.14.0    2019-12-06 [1] CRAN (R 4.0.1)
   R.methodsS3   1.8.1     2020-08-26 [1] CRAN (R 4.0.1)
   R.oo          1.24.0    2020-08-26 [1] CRAN (R 4.0.1)
   R.utils       2.10.1    2020-08-26 [1] CRAN (R 4.0.1)
   R6            2.5.0     2020-10-28 [1] CRAN (R 4.0.1)
   Rcpp          1.0.6     2021-01-15 [1] CRAN (R 4.0.1)
   rematch2      2.1.2     2020-05-01 [1] CRAN (R 4.0.1)
   remotes       2.2.0     2020-07-21 [1] CRAN (R 4.0.1)
   rex           1.2.0     2020-04-21 [1] CRAN (R 4.0.1)
   rlang         0.4.10    2020-12-30 [1] CRAN (R 4.0.1)
   rmarkdown     2.6       2020-12-14 [1] CRAN (R 4.0.1)
   rprojroot     2.0.2     2020-11-15 [1] CRAN (R 4.0.1)
   rstudioapi    0.13      2020-11-12 [1] CRAN (R 4.0.1)
   sessioninfo   1.1.1     2018-11-05 [1] CRAN (R 4.0.1)
   styler        1.3.2     2020-02-23 [1] CRAN (R 4.0.1)
   testthat    * 3.0.1     2020-12-17 [1] CRAN (R 4.0.1)
   tibble        3.0.6     2021-01-29 [1] CRAN (R 4.0.1)
   triebeard     0.3.0     2016-08-04 [1] CRAN (R 4.0.1)
   urltools      1.7.3     2019-04-14 [1] CRAN (R 4.0.1)
   usethis     * 2.0.1     2021-02-10 [1] CRAN (R 4.0.1)
   vcr           0.6.0     2020-12-12 [1] CRAN (R 4.0.1)
   vctrs         0.3.6     2020-12-17 [1] CRAN (R 4.0.1)
   waldo         0.2.3     2020-11-09 [1] CRAN (R 4.0.1)
   webmockr      0.7.4     2020-12-09 [1] CRAN (R 4.0.1)
   whisker       0.4       2019-08-28 [1] CRAN (R 4.0.1)
   withr         2.4.1     2021-01-26 [1] CRAN (R 4.0.1)
   xfun          0.20      2021-01-06 [1] CRAN (R 4.0.1)
   xml2          1.3.2     2020-04-23 [1] CRAN (R 4.0.1)
   yaml          2.2.1     2020-02-01 [1] CRAN (R 4.0.1)

[1] /home/lluis/bin/R/4.0.1/lib/R/library

 R ?? Package was removed from disk.
```
</details>

**Comment by sckott** [comment]
thanks! vcr only supports `crul` and `httr`. that xml call uses `curl` under the hood, which is unlikely to ever be supported 

https://github.com/r-lib/xml2/blob/master/R/xml_parse.R#L94 
then 
https://github.com/r-lib/xml2/blob/master/R/xml_parse.R#L109
then
https://github.com/r-lib/xml2/blob/master/R/paths.R#L9

**Comment by sckott** [comment]
it would be helpful to have a warning or message in these cases, but i don't know yet if that's easy enough to do

**Comment by llrs** [comment]
Now I see your last comment, I'll reopen the issue then. 
I was thinking if it would happen the same if I wanted to test something that reads from: `read.csv("https://myserver.org/myfile.csv")` and other base functions that allow to read from any connection. 

About warning in those cases, perhaps vcr can check if it writes an empty (or just a blank line) cassette and if it does report it that no cassette could be recorded?

**Comment by sckott** [comment]
yeah, you'd think we'd be able to support fxns that request data from a url like read.csv, etc. but since monkey patching in R is not allowed, we can't override code to be able to hijack a http request - we can only do it in httr and crul since they have a hook mechanism within those pkgs to allow the hijacking

> perhaps vcr can check if it writes an empty (or just a blank line) cassette and if it does report it that no cassette could be recorded?

Right, makes sense

**Comment by sckott** [comment]
to do:

- see if it's possible to make a general purpose catcher for when someone uses use_cassette and is not using httr/crul
- if possible, implement a warning or error possibly

**Comment by sckott** [comment]
Hmm. There's not an easy way to do this. An example to look at is test_that that accepts a block of arbitrary R code. When you don't include an `expect_*` call, the whole block is skipped.

```r
test_that("foobar", 5)
#> #> ── Skip (???): foobar ──────────────
Reason: empty test
```

I think the best we can do probably is to look for an empty cassette, and warn/message about that and tell the user what could have gone wrong

**Comment by sckott** [comment]
@llrs if you get a chance to test - reinstall from here and test [your example](https://github.com/ropensci/vcr/issues/224#issue-808011882) again

**Comment by llrs** [comment]
I see that now the empty file is created but a warning is provided with instructions about how to prevent it. I still think it would be nicer if no file were created at all, but this is a nice compromise. Thanks for working on this so fast

**Comment by sckott** [comment]
@llrs okay, reinstall and try again. empty cassettes now cleaned up - and warning is now configureable

**Comment by llrs** [comment]
Great! Many thanks this removes the need to commit empty files and clean them while still ensuring that the end user knows there is a problem. Thanks!!

**Comment by dpprdan** [comment]
One example where having empty cassettes might make sense: 
Consider two functions (or one function with different arguments) make the same web request but return the result differently, e.g. in different formats. Requests are cached with {memoise}, to prevent unnecessary requests. 
I probably would not test two functions in one test and would therefore have two cassettes as well. 
I could use the same cassette twice, I guess, but `check_cassette_names()` would not allow it for good reason. 
The second cassette stays empty, because the request will effectively not be made but returned from the cache. 

I there a better approach to this? I guess I could empty the cache after every test, but that seems a bit disproportionate?

**Comment by sckott** [comment]
Interesting, thanks @dpprdan 

Hmm, if memoise is used then does it make sense to use vcr?  So in the use case you're describing the cassette is always empty?

**Comment by dpprdan** [comment]
> Hmm, if memoise is used then does it make sense to use vcr? 

For the initial request I think it does (and there are not that many identical requests in the tests). We only cache in the same R session. 

> So in the use case you're describing the cassette is always empty?

The second cassette is, yes. The only potential problem I see ATM is that when we delete the first test/request, it is not cached before the second request anymore. Then the second cassette cannot be empty.

**Comment by sckott** [comment]
Can I see the tests? Including which parts are memoized. I'm having a hard time understanding the steps involved

**Comment by dpprdan** [comment]
Of course, they are in this PR: https://github.com/ropensci/opencage/pull/130. 
For example there is a function call that outputs a [list of data.frames](https://github.com/ropensci/opencage/pull/130/files#diff-f6fadc06e67489dac8b34668e44ac23ac064d3949c07e9f27c736ad4d750e93bR29) and the same call that returns a [list of (JSON) lists](https://github.com/ropensci/opencage/pull/130/files#diff-f6fadc06e67489dac8b34668e44ac23ac064d3949c07e9f27c736ad4d750e93bR40).

**Comment by sckott** [comment]
Thanks. I'll have a look

**Comment by dpprdan** [comment]
Maybe reusing cassettes is already enough in most cases?

**Comment by sckott** [comment]
already enough for what?

**Comment by dpprdan** [comment]
Sorry, I meant enough to solve my use-case/problem. When I have an empty cassette, I get a warning. I can look for the cassette with the first request and re-use it for the second request as well (and delete the empty cassette I had for the second request). I'll have no empty cassettes and no warnings then. Problem (probably) solved. 

How about I try this and report back if I encounter a problem?

**Comment by sckott** [comment]
Okay, sounds good.
