### ISSUE TITLE
vcr writes empy cassettes if not run using Run Tests

### ISSUE THREAD

**Issue by llrs** [ropensci/vcr#225]
When I run (just Ctrl+return) a single `test_that` that makes use of `vcr::use_cassette` I get an empty cassette, while when I run it using the Rstudio Run Tests then they are recorded and the cassette has all the information of the requests and reply (Rstudio Version 1.4.1103).

Perhaps this is related to the [note](https://docs.ropensci.org/vcr/index.html#vcr-for-tests): "some users have found different results with `devtools::check()` vs. `devtools::test()`. It’s not clear why this would make a difference"

If #224 is fixed this could be prevented.

<details> <summary><strong>Session Info</strong></summary>

```r
? Session info ????????????????????????????????????????????????????????????????????????
 setting  value                       
 version  R version 4.0.1 (2020-06-06)
 os       Ubuntu 20.04.2 LTS          
 system   x86_64, linux-gnu           
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       Europe/Madrid               
 date     2021-02-15                  

? Packages ????????????????????????????????????????????????????????????????????????????
 ! package     * version   date       lib source        
   assertthat    0.2.1     2019-03-21 [1] CRAN (R 4.0.1)
   base64enc     0.1-3     2015-07-28 [1] CRAN (R 4.0.1)
   BiocManager * 1.30.10   2019-11-16 [1] CRAN (R 4.0.1)
 R bugRzilla   * 0.0.90001 <NA>       [?] <NA>          
   cachem        1.0.3     2021-02-04 [1] CRAN (R 4.0.1)
   callr         3.5.1     2020-10-13 [1] CRAN (R 4.0.1)
   cli           2.3.0     2021-01-31 [1] CRAN (R 4.0.1)
   crayon        1.4.1     2021-02-08 [1] CRAN (R 4.0.1)
   crul          1.0.0     2020-07-30 [1] CRAN (R 4.0.1)
   curl          4.3       2019-12-02 [1] CRAN (R 4.0.1)
   cyclocomp   * 1.1.0     2016-09-10 [1] CRAN (R 4.0.1)
   desc          1.2.0     2018-05-01 [1] CRAN (R 4.0.1)
   devtools    * 2.3.2     2020-09-18 [1] CRAN (R 4.0.1)
   ellipsis      0.3.1     2020-05-15 [1] CRAN (R 4.0.1)
   fastmap       1.1.0     2021-01-25 [1] CRAN (R 4.0.1)
   fauxpas       0.5.0     2020-04-13 [1] CRAN (R 4.0.1)
   fs            1.5.0     2020-07-31 [1] CRAN (R 4.0.1)
   glue          1.4.2     2020-08-27 [1] CRAN (R 4.0.1)
   httpcode      0.3.0     2020-04-10 [1] CRAN (R 4.0.1)
   httr          1.4.2     2020-07-20 [1] CRAN (R 4.0.1)
   jsonlite      1.7.2     2020-12-09 [1] CRAN (R 4.0.1)
   lifecycle     0.2.0     2020-03-06 [1] CRAN (R 4.0.1)
   magrittr      2.0.1     2020-11-17 [1] CRAN (R 4.0.1)
   memoise       2.0.0     2021-01-26 [1] CRAN (R 4.0.1)
   pkgbuild      1.2.0     2020-12-15 [1] CRAN (R 4.0.1)
   pkgload       1.1.0     2020-05-29 [1] CRAN (R 4.0.1)
   prettyunits   1.1.1     2020-01-24 [1] CRAN (R 4.0.1)
   processx      3.4.5     2020-11-30 [1] CRAN (R 4.0.1)
   ps            1.5.0     2020-12-05 [1] CRAN (R 4.0.1)
   purrr         0.3.4     2020-04-17 [1] CRAN (R 4.0.1)
   R6            2.5.0     2020-10-28 [1] CRAN (R 4.0.1)
   Rcpp          1.0.6     2021-01-15 [1] CRAN (R 4.0.1)
   remotes       2.2.0     2020-07-21 [1] CRAN (R 4.0.1)
   rlang         0.4.10    2020-12-30 [1] CRAN (R 4.0.1)
   rprojroot     2.0.2     2020-11-15 [1] CRAN (R 4.0.1)
   rstudioapi    0.13      2020-11-12 [1] CRAN (R 4.0.1)
   sessioninfo   1.1.1     2018-11-05 [1] CRAN (R 4.0.1)
   testthat    * 3.0.1     2020-12-17 [1] CRAN (R 4.0.1)
   triebeard     0.3.0     2016-08-04 [1] CRAN (R 4.0.1)
   urltools      1.7.3     2019-04-14 [1] CRAN (R 4.0.1)
   usethis     * 2.0.1     2021-02-10 [1] CRAN (R 4.0.1)
   vcr           0.6.0     2020-12-12 [1] CRAN (R 4.0.1)
   webmockr      0.7.4     2020-12-09 [1] CRAN (R 4.0.1)
   whisker       0.4       2019-08-28 [1] CRAN (R 4.0.1)
   withr         2.4.1     2021-01-26 [1] CRAN (R 4.0.1)
   xml2          1.3.2     2020-04-23 [1] CRAN (R 4.0.1)
   yaml          2.2.1     2020-02-01 [1] CRAN (R 4.0.1)
```
</details>

**Comment by sckott** [comment]
Yes could be related to check vs. test. 

> When I run (just Ctrl+return) a single test_that that makes use of vcr::use_cassette I get an empty cassette

What was done before that point? Did you run `devtooload::load_all()` or `pkgload::load_all()`? or something else?

**Comment by llrs** [comment]
I did `devtools::load_all()` but just tested with `pkgload::load_all()`and it happens the same. If you need further testing let me know.

**Comment by sckott** [comment]
What does your `vcr_configure()` have for the `dir` parameter? The new `use_vcr()` uses `dir = vcr::vcr_test_path("fixtures")` which should use the correct path whether or not you're in an interactive session or not.

Previous to that change, and which most of my pkgs are like now that use vcr, we had sugggested `dir = "../fixtures"` or `dir = "../fixtures/vcr_cassettes"` - which is a relative path, so in an interactive session, that path would actually be outside of your package one level up.

**Comment by llrs** [comment]
on setup-bugRzilla.R I have `vcr_dir <- vcr::vcr_test_path("fixtures")`.
If I restart the session without running the setup files end on the project directory (which is my working directory). However, if without running the setup file I run the test that uses use_cassette, the fixtures end in the tests/fixtures/ folder, also the empty ones.

**Comment by sckott** [comment]
#224 is fixed so this is less of a problem as at least users will know about an empty cassette now. though it would still be nice to fix this. Working on it

**Comment by sckott** [comment]
@llrs can you reinstall?  then try again. changed to using `here::here` instead of `file.path`, see commit message. Please do let me know if it works now

**Comment by sckott** [comment]
@maelle when you get back from vacation can you test too?

**Comment by maelle** [comment]
This looks good

**Comment by llrs** [comment]
Sorry forgot to test it. Now both ways create and delete the empty cassette.
