### ISSUE TITLE
vcr_configure: new param to quiet all messages

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#226]
e.g., `vcr_configure(..., quiet = TRUE)`

would quiet

- `CrulAdapter enabled`/`HttrAdapter enabled`, in webmockr
- `CrulAdapter disabled`/`HttrAdapter disabled`, in webmockr
- `ejecting casssette`, in vcr

**Comment by dpprdan** [comment]
@sckott since testthat 3e [does not suppress messages anymore](https://testthat.r-lib.org/articles/third-edition.html#messages), would it be a good idea to automatically set `quiet = TRUE` (or otherwise suppress vcr messages) if run with testthat 3e? Maybe testthat sets an appropriate envvar?

**Comment by sckott** [comment]
@dpprdan probably we can set to true - having a look

**Comment by sckott** [comment]
@dpprdan okay, reinstall and try again, default=TRUE now
