### ISSUE TITLE
Does vcr cache things somewhere?

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#228]
Weird behavior seen by @dpprdan and me

* Install vcr dev version
* Use https://github.com/maelle/exemplighratia/pull/2, run tests, then delete fixtures and turn off wifi, run tests: they still pass!

**Comment by maelle** [comment]
@sckott the problem is due to https://github.com/ropensci/vcr/commit/2e07d00d8502e8c78b2a595c880de76094f97fd7

I see that if my package is under blablabla/ropensci/exemplighratia, the fixtures end up at blablabla/ropensci/fixtures

**Comment by sckott** [comment]
thanks, will have a look
