### ISSUE TITLE
insert_cassette when used alone: isn't behaving correctly

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#24]
not stubbing requests as it should ...

**Comment by sckott** [comment]
may push this to the next milestone if needed since major use case will be using `use_cassette` anyway

**Comment by Robsteranium** [comment]
I have a use case for the `insert_cassette` approach. I'd like to use it to power a [knitr chunk hook](https://yihui.org/knitr/hooks/#chunk-hooks) to record http actions in chunks. It's not immediately obvious to me how I'd achieve that with `use_cassette` alone.

You can make this pair of methods work by recreating what happens in `Cassette$call_block`:

```
cassette_name <- "example"

vcr::insert_cassette(cassette_name)
webmockr::webmockr_allow_net_connect()

httr::GET("http://httpbin.org/")

webmockr::webmockr_disable_net_connect()
vcr::eject_cassette(cassette_name)
```

In theory the webmockr toggles could be moved from `Cassette$call_block` to `insert_cassette` and `eject_cassette`. You'd need to explicitly disable/re-enable it to make non-mocked calls while a cassette was inserted (if indeed this is a requirement).

It might just be sufficient to update the docs for `insert_cassette` and `eject_cassette` to explain that you also need to enable/ disable webmockr too.

**Comment by sckott** [comment]
Thanks @Robsteranium - This is great. I think it'd be best if we toggle webmockr with insert/eject methods, i'll try that soon

**Comment by sckott** [comment]
@Robsteranium When you get a chance, can you install `remotes::install_github("ropensci/vcr@rearrange-insert-eject-use")` and try again

**Comment by Robsteranium** [comment]
I can confirm that this works for me too. Thanks!

**Comment by sckott** [comment]
Great, glad it works
