### ISSUE TITLE
GHA failures

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#241]
Not sure why yet

**Comment by sckott** [comment]
@maelle  is this superseded by #242 ?

**Comment by maelle** [comment]
Not sure whether the failures are linked

**Comment by sckott** [comment]
can you link to any of these failing

**Comment by maelle** [comment]
https://github.com/ropensci/vcr/runs/4070341398?check_suite_focus=true

**Comment by sckott** [comment]
Thanks. Oh, i thought you were talking about errors caused by vcr in other repos.

**Comment by sckott** [comment]
fixed now

**Comment by maelle** [comment]
thanks a ton!
