### ISSUE TITLE
Fix encoding issues [critical]

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#245]
see email from Tomas Kalibera

**Comment by llrs** [comment]
There was a new release a couple of days ago (2022-11-04). Is this issue fixed (whatever it was) ?

I'm exploring the issues of vcr because at the moment I am experiencing an error in the tests of rtweet which seems to come from vcr latest update.

**Comment by sckott** [comment]
no, not fixed. cran emailed again about that docs html update thing and I had to submit a new version for that. 

ive got very little time to work on this, and it's super hard to figure out whats going on. if memory serves, the solution I want to go with is moving everyone to use JSON for serialization to disk because the error I think is coming from the yaml pkg which has a lot of problems.

**Comment by KevCaz** [comment]
FWIW, I have some errors with rcites that seem related (I can give you more details if relevant) I am now using `serialize_with = "json"` in `vcr::vcr_configure()`, I'll report back here if it fixes the issue with the CRAN.

**Comment by KevCaz** [comment]
It was a separate issue, sorry, it looks like there is something wrong with cassettes that have a 401 error code. Will investigate further, but I will still opt for json over yaml.

**Comment by sckott** [comment]
Thanks @KevCaz ! Let me know about the 401 thing. 

There's definitely a few issues: 

1. One is related to base64. I moved to using an explicit string in cassettes called `base64_string`  when you specify `preserve_exact_body_bytes = TRUE` - but somehow forgot to account for existing cassettes that have the old string `string` in their cassettes (which held both base64 and non-base64 encoded strings)
2. The other is that the c++ function for splitting strings is causing issues - at least locally for me, so replacing that with plain R code

**Comment by KevCaz** [comment]
Cannot help with 1. but for 2. the function seems to work properly for me (locally).

**Comment by sckott** [comment]
@KevCaz glad the c++ fxn is not causing issues for you. i'm replacing it anyway, just cause its easy enough to do with pure R, and no reason to require compilation for such a trivial use case.

**Comment by sckott** [comment]
could never sort this out and haven't heard about this again, closing
