### ISSUE TITLE
provide option to suppress all messages

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#25]

**Comment by maelle** [comment]
Not that I have time at the moment :crying_cat_face: but this and #110 seem perfect issues to dive into the package code! 

* Find all current messages and wrap them like usethis does maybe (usethis.silent/vcr.silent)
* Add more messages

**Comment by sckott** [comment]
good idea - and I added a label https://github.com/ropensci/vcr/labels/informing-the-user - ther's a third one too

**Comment by sckott** [comment]
i think this is addressed in https://github.com/ropensci/vcr/issues/226
