### ISSUE TITLE
Overview of fixes for upcoming v1.2

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#255]
So that we have a single place to go to discuss what's needed to submit a fixed version of vcr to cran:

- [x] Remove c++ string splitting function. I know this wasn't a problem for everyone but caused issues in some places, and figured nice to remove it since its a simple case and nice to not require compliation - on the terribly named branch `various-fixes`. **This is done, on master now**
- [x] In the version on cran right now, i included a change to how we record base64 encoded strings when users supply `preserve_exact_body_bytes = TRUE` to `use_cassette` or `vcr_configure`. The change was that when `preserve_exact_body_bytes = TRUE` we'd write the encoded string into the yaml or json field `base64_string` instead of just `string`. However, and this is completely my fault, I forgot to account for existing cassettes that are using `preserve_exact_body_bytes = TRUE` but have encoded strings in the `string` field. On terribly named branch `various-fixes` I'm working on fixing this; it's a bit of a hard one, but hopefully i'll get it sorted soon. **This is done, on master now**
- [x] #249 An error is being thrown for empty cassettes, there's a proposed fix for this in PR #252 - i'll have a look at this asap
- [x] #253 hoping to include change of master to main before submitting this version (via https://jarv.is/notes/github-rename-master/)

cc @dpprdan @maelle @llrs @KevCaz @jhnwllr

**Comment by maelle** [comment]
https://usethis.r-lib.org/reference/git-default-branch.html

**Comment by sckott** [comment]
@dpprdan @maelle @llrs @KevCaz 

we're on main now

can you test vcr on main with any packages you have that use vcr? let me know if any issues

**Comment by KevCaz** [comment]
@sckott looks like there is still an issue with token (one test I use in rcites), here is a reprex with the latest commit:

```r
test_that('problem with auth', {
  vcr::use_cassette('wrong_token', {
    res <- httr::GET("https://httpbin.org/bearer")
  })
  expect_true(res$status_code == 401)
})
```

I get

**Comment by sckott** [comment]
thanks @KevCaz - not sure what's going on there, taking a look

**Comment by llrs** [comment]
On rtweet vcr worked as expected without problems. 
Somewhat related, I also changed the configuration to use .json instead of the default .yml for the fixtures #245. Will this be the way forward?

**Comment by sckott** [comment]
thanks @llrs - yes, I think json is the way forward. json is not as easy to read (you have to prettify it first) - but other than that going with json i think is the way to go

**Comment by juliasilge** [comment]
The qualtRics package is [also impacted](https://cran.r-project.org/web/checks/check_results_qualtRics.html) by the recent vcr changes. I just installed the current GitHub version of vcr via `devtools::install_github("ropensci/vcr")` and currently what I see on checking is:

```── Test failures ───────────────────────────────────────────────────────────────────────────────────────── testthat ────

> library(testthat)
> library(qualtRics)
> 
> test_check("qualtRics")
  |======================================================================| 100%
  |======================================================================| 100%
  |======================================================================| 100%
  |======================================================================| 100%
  |======================================================================| 100%
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 224 ]

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-fetch-distributions.R:5'): fetch_distributions returns a tbl_df with expected column names and types ──
Error in `nchar(x)`: invalid multibyte string, element 1
Backtrace:
     ▆
  1. └─vcr::use_cassette(...) at test-fetch-distributions.R:5:2
  2.   └─vcr::insert_cassette(...)
  3.     └─Cassette$new(...)
  4.       └─vcr (local) initialize(...)
  5.         └─self$http_interactions()
  6.           ├─HTTPInteractionList$new(...)
  7.           │ └─vcr (local) initialize(...)
  8.           └─self$previously_recorded_interactions()
  9.             ├─vcr:::compact(...)
 10.             │ └─base::Filter(Negate(is.null), x)
 11.             │   ├─base::unlist(lapply(x, f))
 12.             │   └─base::lapply(x, f)
 13.             └─base::lapply(...)
 14.               └─vcr (local) FUN(X[[i]], ...)
 15.                 ├─VcrResponse$new(...)
 16.                 │ └─vcr (local) initialize(...)
 17.                 │   └─base::inherits(body, "list")
 18.                 └─z$response$body$string %||% z$response$body$base64_string

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 224 ]
Error: Test failures
Execution halted

1 error ✖ | 0 warnings ✔ | 0 notes ✔
Error: R CMD check found ERRORs
Execution halted

Exited with status 1.
```

Let me know if there is anything else I should do or try.

**Comment by sckott** [comment]
thanks @juliasilge - having a look

**Comment by sckott** [comment]
looking into this, down the stack getting calls to `nchar` and `gsub` throwing multibyte errors - looking into those

**Comment by maelle** [comment]
Just checked that {nasapower} tests all pass with the dev version of vcr. :heavy_check_mark: (they don't pass with the CRAN version)

**Comment by sckott** [comment]
great! thanks @maelle

**Comment by sckott** [comment]
sorry y'all was hoping to get time on this today, but nanny called in sick

**Comment by sckott** [comment]
@KevCaz is `vcr` on main working for `rmangal`?

**Comment by KevCaz** [comment]
@sckott yes all good for `rmangal`! Thanks!

**Comment by sckott** [comment]
great, thanks @KevCaz

**Comment by sckott** [comment]
regarding @juliasilge  issue: in the internal function `is_base64` we are now checking if the user is setting `preserve_exact_body_bytes=TRUE` && using `string` - then we're calling it base64 encoded - in qualtrics your using it globally for all tests - so we're assuming the response body strings are base64 encoded. But the string definitely isn't in fetch_distributions - its just a plain string - so I am trying to figure out how to deal with this case

**Comment by sckott** [comment]
@juliasilge would you be willing to submit a new version to CRAN to address this issue with your pkg?  I'm not seeing it in any other pkgs. I could make a change in vcr for this case, but i've found it really difficult to figure out a fix because detecting base64 is not easy. If you are willing, you just need to re-record the cassette associated with the failing test above you shared - and ideally re-record all test fixtures (b/c 1. the new vcr setup records base64 encoded data to `base64_string` rather than `string`, and 2. it's a good idea to re-record every so often). Note that you do have `preserve_exact_body_bytes = TRUE` set across all of your tests, whereas i think the fetch distributions one is the only one that has a plain json string rather than base64 encoded string.

**Comment by juliasilge** [comment]
@sckott I am happy to submit a new version to CRAN but unfortunately I cannot regenerate many (most?) of the test fixtures. I don't have access to many of the features that are tested in the package. I put out a call in ropensci/qualtRics#293 to see if someone is able to do that. I'll give that a few days and if no one is able to help on that, I'll take the test out and resubmit, leaving the issue open to see if we can add it back later.

**Comment by sckott** [comment]
Thanks @juliasilge

**Comment by sckott** [comment]
revdepchecks all good

**Comment by sckott** [comment]
submitting now
