### ISSUE TITLE
Author/contributor?

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#258]
two issues:

1. i think we should change all folks in DESCRIPTION to `aut` from `ctb`. My understanding is that if we do that your name will show up in the citation for the package, which I think is warranted for any author/contributor. 
2. @dpprdan okay to make you an author on vcr?

@maelle @aaronwolen

**Comment by aaronwolen** [comment]
Totally cool with me 👍

**Comment by sckott** [comment]
great, thanks @aaronwolen

**Comment by dpprdan** [comment]
More than okay, thanks!

**Comment by sckott** [comment]
great
