### ISSUE TITLE
Vignette is out of sync with docs

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/vcr#260]
https://docs.ropensci.org/vcr/articles/configuration.html#serialize_with is out of sync with the docs:

> `serialize_with`: (character) "yaml" or "json". Note that you can have multiple cassettes with the same name as long as they use different serializers; so if you only want one cassette for a given cassette name, make sure to not switch serializers, or clean up files you no longer need.

**Comment by sckott** [comment]
thanks @adamhsparks ! 

i'll get it fixed

**Comment by maelle** [comment]
@sckott https://github.com/ropensci/vcr/blob/6da4637ff62d3b3696d32913e7652524cb97690a/man/rmdhunks/configuration-vignette.Rmd#L86 needs to be updated I think?

The commit status for ropensci-docs is green so all should be good on that side.

**Comment by sckott** [comment]
thanks @maelle ! i was only looking at the function docs, thanks for catching that. pushed, will check and see if the docs build is updatd soon

**Comment by sckott** [comment]
updated https://docs.ropensci.org/vcr/articles/configuration.html#serialize_with - look good @adamhsparks ?

**Comment by adamhsparks** [comment]
It’s in sync, but there’s a typo that I now see, "Which serializer to use. “yaml” or “json”. “, should probably be "Which serializer to use, “yaml” or “json”."

**Comment by sckott** [comment]
thanks, will fix
