### ISSUE TITLE
At what level does stubbing occur?

### ISSUE THREAD

**Issue by hadley** [ropensci/vcr#35]
The readme talks about "HTTP requests", but in insufficient detail for me to predict what it captures. Requests made by base R? By curl? By httr? By something else? Some more detail would be helpful.

Relatedly, I think you need to move the basic example up much higher on the page.

**Comment by sckott** [comment]
👋 Good questions. I'll clear up these details in the README. 

- In the end, it should be able to support requests from any http R client. Right now only `crul` is supported. The integration comes not here, but through `webmockr` - see  https://github.com/ropensci/webmockr/blob/master/R/adapter-crul.R - I've been meaning to make an adapter for `httr` in `webmockr`, started on it a while back here  https://github.com/ropensci/webmockr/blob/master/inst/ignore/adapter-httr.R but now that you've added that callback functionality I need to revisit it
- Good suggestion on moving the basic example up. Will do.
- In terms of how it works, which I think you are asking about, `vcr` uses `webmockr` (via an adapter (e.g., https://github.com/ropensci/webmockr/blob/master/R/adapter-crul.R)) to capture the request before it's executed, stub the request using `webmockr`, then allowing a single real HTTP request, and caches that (e.g., https://github.com/ropensci/rredlist/blob/with-vcr/tests/fixtures/vcr_cassettes/rl_common_names_low_level.yml). On subsequent requests the cached response is used. 

I'm at the stage of using `vcr` in test suites in some of my packages - and working out bugs found via that process. The two so far are: [rredlist](https://github.com/ropensci/rredlist/tree/with-vcr/tests) and [bold](https://github.com/ropensci/bold/tree/with-vcr/tests) - Hopefully pretty close to first cran push
