### ISSUE TITLE
Toggle vcr on/off across all tests 

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#37]
seems like could be really useful - maybe passing an env var while running `devtools::test()` that will just ignore vcr cassettes

**Comment by maelle** [comment]
I think my question #117 is related to this.

**Comment by maelle** [comment]
Then on Travis for instance I'd have a build with the environment variable IGNORE_VCR_CASSETTE set to TRUE. 🙂

**Comment by sckott** [comment]
right, thanks for pinging in here. will look into this soon. Would be good to have this as a workflow option

**Comment by sckott** [comment]
the parameter `ignore_cassettes` in `vcr_configure`

**Comment by maelle** [comment]
How would you make that work for a single build on Travis? (all builds but one using the cassettes).

**Comment by sckott** [comment]
@maelle using an env var in matrix i think? e.g., https://github.com/ropensci/vcr/blob/master/.travis.yml#L10 does that make sense or no?

**Comment by sckott** [comment]
@maelle okay, this should work now, see `?lightswitch` after reinstalling

**Comment by maelle** [comment]
sorry, I didn't work on hubspot this week, I'll try it next week, thanks a ton!

**Comment by maelle** [comment]
I'm setting this up at last, thanks. I have two remarks

* I am not sure I fully understand the differences VCR_TURN_OFF vs VCR_TURNED_OFF, could you give examples of combinations of environment variables values and why one would use them?

* I like to link https://rstats.wtf/r-startup.html for startup.

**Comment by sckott** [comment]
vcr_turn_off is a short-hand for vcr_turned_off and ignore_cassettes, see  https://github.com/ropensci/vcr/blob/master/R/lightswitch.R#L120-L129 - so it sets both - you can achieve the same thing as vcr_turn_off by setting both vcr_turned_off and ignore_cassettes - i can't remember exactly why - but anyway, I'll document it better
