### ISSUE TITLE
Scanner error: while scanning a plain scalar ... found a tab character that violate intendation

### ISSUE THREAD

**Issue by amoeba** [ropensci/vcr#51]
I just created a test that makes use of vcr that tests the status code and response body size against an ~ 8 MiB file and got this error while running `devtools::test()`. 

> (../fixtures/vcr_cassettes/get_object.yml) Scanner error: while scanning a plain scalar at line 35, column 1 found a tab character that violate intendation at line 36, column 1

The line causing the YAML parsing issue is the second line of the XML document that is returned in the response body so this totally makes sense. 

```text
32	    body:
33	      encoding: UTF-8
34	      string: <?xml version="1.0" encoding="utf-8"?>
35	<ns0:MD_Metadata id="de.pangaea.dataset691332" xmlns:ns0="http://www.isotc211.org/2005/gmd" xmlns:ns2="http://www.isotc211.org/2005/gco" xmlns:ns3="http://www.opengis.net/gml" 
```

See the saved fixture at https://github.com/amoeba/dataonecrul/blob/master/tests/fixtures/vcr_cassettes/get_object.yml

I'm not overly familiar with the parsing of YAML but I'd be happy to look into this if you're not immediately aware of an easy fix. Possibly just doing some YAML-specific escaping?

<details> <summary><strong>devtools::test() output</strong></summary>

> devtools::test()
Loading dataonecrul
Testing dataonecrul
✔ | OK F W S | Context
✖ |  0 1     | getObject [2.3 s]
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test_get_object.R:11: error: test a system metadata request works
(../fixtures/vcr_cassettes/get_object.yml) Scanner error: while scanning a plain scalar at line 35, column 1 found a tab character that violate intendation at line 36, column 1
1: vcr::use_cassette("get_object", {
       resp <- get_object(node, "8f096d0c7e2f5962ce4828cc6ea59572")
       expect_equal(resp$status_code, 200)
       expect_length(resp$content, 8731184)
   }) at /Users/bryce/src/dataonecrul/tests/testthat/test_get_object.R:11
2: insert_cassette(name, record = record, match_requests_on = match_requests_on, re_record_interval = re_record_interval, tag = tag, tags = tags, update_content_length_header = update_content_length_header, 
       decode_compressed_response = decode_compressed_response, allow_playback_repeats = allow_playback_repeats, allow_unused_http_interactions = allow_unused_http_interactions, 
       exclusive = exclusive, serialize_with = serialize_with, persist_with = persist_with, preserve_exact_body_bytes = preserve_exact_body_bytes)
3: Cassette$new(name = name, record = record, match_requests_on = match_requests_on, re_record_interval = re_record_interval, tag = tag, tags = tags, update_content_length_header = update_content_length_header, 
       decode_compressed_response = decode_compressed_response, allow_playback_repeats = allow_playback_repeats, allow_unused_http_interactions = allow_unused_http_interactions, 
       exclusive = exclusive, serialize_with = serialize_with, persist_with = persist_with, preserve_exact_body_bytes = preserve_exact_body_bytes)
4: .subset2(public_bind_env, "initialize")(...)
5: self$http_interactions()
6: HTTPInteractionList$new(interactions = self$previously_recorded_interactions(), request_matchers = vcr_configuration()$match_requests_on)
7: .subset2(public_bind_env, "initialize")(...)
8: self$previously_recorded_interactions()
9: compact(lapply(self$deserialized_hash()[["http_interactions"]], function(z) {
       response <- VcrResponse$new(z$response$status$code, z$response$headers, z$response$body$string)
       if (self$update_content_length_header) 
           response$update_content_length_header()
       zz <- HTTPInteraction$new(request = Request$new(z$request$method, z$request$uri, z$request$body$string, z$request$headers), response = response)
       hash <- zz$to_hash()
       if (request_ignorer$should_be_ignored(hash$request)) 
           NULL
       else hash
   }))
10: Filter(Negate(is.null), x)
11: unlist(lapply(x, f))
12: lapply(x, f)
13: lapply(self$deserialized_hash()[["http_interactions"]], function(z) {
       response <- VcrResponse$new(z$response$status$code, z$response$headers, z$response$body$string)
       if (self$update_content_length_header) 
           response$update_content_length_header()
       zz <- HTTPInteraction$new(request = Request$new(z$request$method, z$request$uri, z$request$body$string, z$request$headers), response = response)
       hash <- zz$to_hash()
       if (request_ignorer$should_be_ignored(hash$request)) 
           NULL
       else hash
   })
14: self$deserialized_hash()
15: self$serializer$deserialize_path()
16: yaml::yaml.load_file(self$path)
17: yaml.load(readLines(con), error.label = error.label, ...)
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔ |  1   1   | SystemMetadata [0.1 s]
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
test_get_system_metadata.R:9: warning: test a system metadata request works
more than 1 found, using first
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 2.5 s

OK:       1
Failed:   1
Warnings: 1
Skipped:  0

</details>

<details> <summary><strong>Session Info</strong></summary>

```r
> devtools::session_info()
Session info ----------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.4 (2018-03-15)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.2.550)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Juneau              
 date     2018-04-25                  

Packages --------------------------------------------------------------------------------------------------------------------------------------------
 package     * version    date       source                            
 assertthat    0.2.0      2017-04-11 CRAN (R 3.4.0)                    
 backports     1.1.2      2017-12-13 CRAN (R 3.4.3)                    
 base        * 3.4.4      2018-03-15 local                             
 base64enc     0.1-3      2015-07-28 CRAN (R 3.4.0)                    
 cli           1.0.0      2017-11-05 CRAN (R 3.4.2)                    
 clisymbols    1.2.0      2017-05-21 CRAN (R 3.4.0)                    
 commonmark    1.4        2017-09-01 CRAN (R 3.4.1)                    
 compiler      3.4.4      2018-03-15 local                             
 crayon        1.3.4      2017-09-16 CRAN (R 3.4.1)                    
 crul          0.5.2      2018-02-24 CRAN (R 3.4.3)                    
 curl          3.2        2018-03-28 CRAN (R 3.4.4)                    
 dataonecrul * 0.1.0      <NA>       local                             
 datasets    * 3.4.4      2018-03-15 local                             
 desc          1.1.1      2017-08-03 CRAN (R 3.4.1)                    
 devtools      1.13.5     2018-02-18 CRAN (R 3.4.3)                    
 digest        0.6.15     2018-01-28 CRAN (R 3.4.3)                    
 evaluate      0.10.1     2017-06-24 CRAN (R 3.4.1)                    
 gh            1.0.1      2017-07-16 CRAN (R 3.4.1)                    
 git2r         0.21.0     2018-01-04 CRAN (R 3.4.3)                    
 graphics    * 3.4.4      2018-03-15 local                             
 grDevices   * 3.4.4      2018-03-15 local                             
 htmltools     0.3.6      2017-04-28 CRAN (R 3.4.0)                    
 httr          1.3.1      2017-08-20 CRAN (R 3.4.1)                    
 ini           0.3.0      2017-09-30 CRAN (R 3.4.2)                    
 jsonlite      1.5        2017-06-01 CRAN (R 3.4.0)                    
 knitr         1.20       2018-02-20 CRAN (R 3.4.3)                    
 lazyeval      0.2.1      2017-10-29 CRAN (R 3.4.2)                    
 magrittr      1.5        2014-11-22 CRAN (R 3.4.0)                    
 memoise       1.1.0      2017-04-21 CRAN (R 3.4.0)                    
 methods     * 3.4.4      2018-03-15 local                             
 R6            2.2.2      2017-06-17 CRAN (R 3.4.0)                    
 Rcpp          0.12.16    2018-03-13 CRAN (R 3.4.4)                    
 remotes       1.1.1      2017-12-20 CRAN (R 3.4.3)                    
 rlang         0.2.0      2018-02-20 CRAN (R 3.4.3)                    
 rmarkdown     1.9        2018-03-01 CRAN (R 3.4.3)                    
 roxygen2      6.0.1      2017-02-06 CRAN (R 3.4.0)                    
 rprojroot     1.3-2      2018-01-03 CRAN (R 3.4.3)                    
 rstudioapi    0.7        2017-09-07 CRAN (R 3.4.1)                    
 stats       * 3.4.4      2018-03-15 local                             
 stringi       1.1.7      2018-03-12 CRAN (R 3.4.4)                    
 stringr       1.3.0      2018-02-19 CRAN (R 3.4.3)                    
 testthat    * 2.0.0      2017-12-13 CRAN (R 3.4.3)                    
 tools         3.4.4      2018-03-15 local                             
 triebeard     0.3.0      2016-08-04 cran (@0.3.0)                     
 urltools      1.7.0      2018-01-20 cran (@1.7.0)                     
 usethis       1.3.0      2018-02-24 CRAN (R 3.4.3)                    
 utils       * 3.4.4      2018-03-15 local                             
 vcr         * 0.0.7.9431 2018-04-25 Github (ropensci/vcr@0b80323)     
 webmockr      0.2.2.9112 2018-04-25 Github (ropensci/webmockr@6d7e6ea)
 withr         2.1.2      2018-03-15 CRAN (R 3.4.4)                    
 xml2          1.2.0      2018-01-24 CRAN (R 3.4.3)                    
 yaml          2.1.18     2018-03-08 CRAN (R 3.4.4)  
```
</details>

**Comment by sckott** [comment]
thanks! for this

can you try  `preserve_exact_body_bytes` (it converts raw characters to base64) and see if that fixes it?

```r
vcr::use_cassette("cassette-name", {
    your code
}, preserve_exact_body_bytes = TRUE)
```

I definitely want to make sure XML response bodies work as plain text, but want to see if storing as base64 helps

**Comment by amoeba** [comment]
That got the error to go away after removing the related fixture and changing that argument. Thanks! 

Though now I'm seeing that my cassette isn't getting used:

```
Testing dataonecrul
✔ | OK F W S | Context
✔ |  2       | getObject [12.8 s]
✔ |  1       | SystemMetadata
```

**Comment by sckott** [comment]
hmm, this warning `more than 1 found, using first` shouldn't be happening, since it's commented out in the latest on github, see https://github.com/ropensci/vcr/blob/master/R/http_interaction_list.R#L153

but your session info does say you have the latest, weird

**Comment by amoeba** [comment]
Is it also weird that the testthat output shows two tests were run even though I only have one `test_that` block in that test file?

**Comment by sckott** [comment]
@amoeba i'm still working out some issues with that duplication. inspecting logs and such to see where we're not doing something right

**Comment by amoeba** [comment]
Np, and thanks!

**Comment by sckott** [comment]
> Is it also weird that the testthat output shows two tests were run even though I only have one test_that block in that test file?

isn't the count in testthat output for each expectation (e.g., `expect_equal`), not `test_that` block?

**Comment by amoeba** [comment]
> isn't the count in testthat output for each expectation (e.g., expect_equal), not test_that block?

ah, that makes more sense.

Just tried it again and no luck. First run:

```
==> devtools::test()

Loading dataonecrul
Loading required package: testthat
Loading required namespace: jsonlite
Testing dataonecrul
✔ | OK F W S | Context
✔ |  2       | getObject [10.0 s]
✔ |  1       | SystemMetadata [1.2 s]

══ Results ════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 11.2 s

OK:       3
Failed:   0
Warnings: 0
Skipped:  0

```

Second run:

```
==> devtools::test()

Loading dataonecrul
Loading required package: testthat
Loading required namespace: jsonlite
Testing dataonecrul
✔ | OK F W S | Context
✔ |  2       | getObject [5.0 s]
✔ |  1       | SystemMetadata

══ Results ════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 5.1 s

OK:       3
Failed:   0
Warnings: 0
Skipped:  0
```

<details>
<summary>devtools::session_info()</summary>

```
> devtools::session_info()
Session info ----------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.447)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/Juneau              
 date     2018-04-30                  

Packages --------------------------------------------------------------------------------------------------
 package    * version    date       source                            
 base       * 3.5.0      2018-04-24 local                             
 base64enc    0.1-3      2015-07-28 CRAN (R 3.5.0)                    
 compiler     3.5.0      2018-04-24 local                             
 curl         3.2        2018-03-28 CRAN (R 3.5.0)                    
 datasets   * 3.5.0      2018-04-24 local                             
 devtools     1.13.5     2018-02-18 CRAN (R 3.5.0)                    
 digest       0.6.15     2018-01-28 CRAN (R 3.5.0)                    
 git2r        0.21.0     2018-01-04 CRAN (R 3.5.0)                    
 graphics   * 3.5.0      2018-04-24 local                             
 grDevices  * 3.5.0      2018-04-24 local                             
 httr         1.3.1      2017-08-20 CRAN (R 3.5.0)                    
 jsonlite     1.5        2017-06-01 CRAN (R 3.5.0)                    
 knitr        1.20       2018-02-20 CRAN (R 3.5.0)                    
 lazyeval     0.2.1      2017-10-29 CRAN (R 3.5.0)                    
 magrittr     1.5        2014-11-22 CRAN (R 3.5.0)                    
 memoise      1.1.0      2017-04-21 CRAN (R 3.5.0)                    
 methods    * 3.5.0      2018-04-24 local                             
 R6           2.2.2      2017-06-17 CRAN (R 3.5.0)                    
 Rcpp         0.12.16    2018-03-13 CRAN (R 3.5.0)                    
 rstudioapi   0.7        2017-09-07 CRAN (R 3.5.0)                    
 stats      * 3.5.0      2018-04-24 local                             
 tools        3.5.0      2018-04-24 local                             
 triebeard    0.3.0      2016-08-04 cran (@0.3.0)                     
 urltools     1.7.0      2018-01-20 cran (@1.7.0)                     
 utils      * 3.5.0      2018-04-24 local                             
 vcr        * 0.0.8.9534 2018-04-30 Github (ropensci/vcr@ba32bc9)     
 webmockr   * 0.2.2.9119 2018-04-30 Github (ropensci/webmockr@34fae0c)
 withr        2.1.2      2018-03-15 CRAN (R 3.5.0)                    
 yaml         2.1.18     2018-03-08 CRAN (R 3.5.0) 
````
</details>

**Comment by sckott** [comment]
no luck? looks like it worked to me, from 11 sec to 5 sec

**Comment by sckott** [comment]
Good point. Though I think you're still seeing 5 sec of time there because the function is still doing something with the cached data, maybe it's all yaml loading time, i can take a look

**Comment by sckott** [comment]
tried `profvis`, but didn't glean anything from that right away. 

At least on my machine, the yml file for that test file is ~10 mb, so pretty big, which I think explains the test time, let me know if you think that's wrong.

**Comment by amoeba** [comment]
Ah! I turned off my WiFi and the test still ran and succeeded. Also still shows a ~5s time so I think we know it's not making a network request that takes 5s.

**Comment by sckott** [comment]
nice, yeah, looking forward to still being able to run my tests on all my pkgs when on a plane 😼

**Comment by amoeba** [comment]
Yeah that's handy. Thanks for the quick fix. Can I close this and maybe open up a new issue for the slow fixture load time?

**Comment by sckott** [comment]
sound good
