### ISSUE TITLE
Add user setup fxn

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#52]
to write in the user's package:

- `helper-packagename.R` file with 

```r
# set up vcr
library("vcr")
invisible(vcr::vcr_configure(dir = "../fixtures/vcr_cassettes"))
```

- update DESCRIPTION with `vcr` and `webmockr` in Suggests
- a dummy test file with an example? and state "delete me after looking at this"

--------

- directory creation happens automatically, so we don't need to help with that.

**Comment by maelle** [comment]
yesss that'd be grand. I read the issue tracker looking for this in case it hadn't been suggested yet!

I wonder how much the test writing could also be automated.

**Comment by sckott** [comment]
hoping to get this done soon. 

> I wonder how much the test writing could also be automated.

what do you mean?

**Comment by maelle** [comment]
Well once you've written your functions accessing an API, how much the tests can be drafted for you. I think it's not very possible.

**Comment by sckott** [comment]
in theory possible. Though in practice out of scope here, but more important I think tests are so specific to a library that it'd be hard to do a good job automating it

**Comment by sckott** [comment]
@maelle if you have time can you try `vcr_setup`?

```r
remotes::install_github("ropensci/vcr@user-setup")
library(vcr)
?vcr_setup
```

run on a package you have already, OR there's an example in the docs for `vcr_setup` that doesn't work entirely yet

**Comment by maelle** [comment]
Yay, running it now on a branch of `ropenaq`! First thought: maybe the function should be called `use_vcr()` for aligning its name with `usethis`-like functions? Not only `usethis` functions, but also e.g. `travis::use_tic()` have such names.

**Comment by maelle** [comment]
By default `vcr_setup()` should run on the current project (or on the current directory if there's no project cf `usethis::proj_get()`).

**Comment by maelle** [comment]
A few other suggestions
- Should the helper-ropenaq.R file have "vcr" in its name?
- What's tests/test-all.R?
- Should the function end with a message about the best place where to read about what next to do, i.e. where next to best learn about using `vcr`?

End of suggestions :-)

**Comment by sckott** [comment]
thx for trying it! 

i'll think about a name change. 

agree that current directory seems smart. 

> Should the helper-ropenaq.R file have "vcr" in its name?

it could, though I thought it made sense to take advantage of the helper file function that already existed. do you think it is worth adding a separate file for vcr setup?

> What's tests/test-all.R?

it's this file https://github.com/r-lib/testthat/blob/master/tests/testthat.R - I think the name doesn't matter really, AFAIK. instead I could just look for any `.R` file under `tests` that has a `test_check` call 

> Should the function end with a message about the best place where to read about what next to do, i.e. where next to best learn about using `vcr`?

yeah, good thinking

**Comment by maelle** [comment]
testthat uses setup.R for setup I think?

**Comment by sckott** [comment]
what is setup.R?

**Comment by maelle** [comment]
Oops scrap that setup() is actually a testthat function.
