### ISSUE TITLE
Add ability to force encoding 

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#65]
```ruby
VCR.configure do |c|
  c.before_record do |i|
    i.response.body.force_encoding('UTF-8')
  end
end
```

needs to probably wait in general  for before record and after record hooks to work

**Comment by maelle** [comment]
doesn't the current code force encoding?

**Comment by sckott** [comment]
Right, I guess we do force to utf-8 already when parsing the body. the example above from ruby vcr is used in a before record hook - see https://relishapp.com/vcr/vcr/v/5-1-0/docs/hooks/before-record-hook - hooks in vcr don't work yet. i'll close this issue and open a new issue to get hooks done
