### ISSUE TITLE
Warn users of possible sensitive data 

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#82]
Could look for keywords like key/token etc and throw warning if found

**Comment by sckott** [comment]
probably don't want to have this at normal run time unless really fast. 

could start off with a separate function

**Comment by maelle** [comment]
maybe `use_vcr()` should add a link to the docs about sensitive data. I.e. another explicit item after the item called `learn_more`.

```r
secrets_protection = paste0(
    "If your package uses secrets such as API keys read this chapter to know how to handle them securely:\n   ",
    "https://books.ropensci.org/http-testing/security.html"
  )
)
```

**Comment by sckott** [comment]
Yes, good idea!

**Comment by maelle** [comment]
this is a good alternative/complement to #182

**Comment by sckott** [comment]
not doing this
