### ISSUE TITLE
Maybe change suggested use_cassette usage?

### ISSUE THREAD

**Issue by sckott** [ropensci/vcr#86]
I have been doing (assume the `expect_is` call fails)

```r
test_that("foobar works", {
    vcr::use_cassette("foobar", {
        a <- foobar()
        expect_is(a, "character")
    })
})
```

But when the `expect_is` line fails, the traceback gives the line for the `vcr::use_cassette` call, instead of the `expect_is` line. 

if we change to:

```r
vcr::use_cassette("foobar", {
  test_that("foobar works", {
      a <- foobar()
      expect_is(a, "character")
  })
})
```

the traceback points to the actual test line that failed

----

Make sure this doesn't lead to othe problems

**Comment by dpprdan** [comment]
Wouldn't this also be an option?

```r
test_that("foobar works", {
    vcr::use_cassette("foobar", {
        a <- foobar()
    })
    expect_is(a, "character")
})
```

Or rather, is there a problem with it, I am not seeing ATM? Traceback seems to work with it.

**Comment by sckott** [comment]
You're right. Thanks for the ping on this. I'll add to the docs the various ways you can arrange the code blocks and test lines

**Comment by sckott** [comment]
https://github.com/ropensci/vcr#best-practices
